# Generated by Django 4.2.3 on 2023-07-21 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80)),
                ('capacite', models.PositiveIntegerField()),
                ('equipement', models.CharField(max_length=500)),
                ('prix', models.IntegerField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Salle',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=16)),
                ('mot_de_passe', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('salle_reservee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Reservations.salle')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservation',
            },
        ),
    ]
